services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: vacancyhunter
    ports:
     - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d vacancyhunter"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - "pgdata:/var/lib/postgresql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8283:8080
    depends_on:
      db:
        condition: service_healthy

  vacancyhunter:
    image: vacancyhunter
    build: .
    ports:
      - 8382:8000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "vacancyhunterdata:/app/media"

volumes:
  pgdata:
  vacancyhunterdata: